spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lively?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  security:
    user:
      name: "admin"
      password: "admin"

  output:
    ansi:
      enabled: always

  config:
    import: classpath:secrets.properties
