spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lively?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
